### ISSUE TITLE
could you share the backend code or service?

### ISSUE THREAD

**Issue by dongzhi-yang** [kaihendry/sg-anpr#1]
Hi Kaihendry
I've been through the code, but I am not able to figure out the back end code or service that does the real job.  Could you share it?
Thanks
Don

**Comment by kaihendry** [comment]
My code is a front end for https://hub.docker.com/r/openalpr/openalpr/ which is referenced in the code :P

**Comment by dongzhi-yang** [comment]
Thanks for the quick response! Just one more question, on its website, http://www.openalpr.com/cloud-api.html, in the supported countries list, there is no 'Singapore',  but in your link, I tried with a couple of Singapore license plates from google image, they work.  Did you add any training images yourself? 
You also mentioned that you wanted to do malaysian plates, but the link directs me to another youtube video of yours:)

**Comment by kaihendry** [comment]
There is some SG training stuff in the upstream code, but it's probably not in a good enough state for them to build a service supporting.

If you watched my awesome Youtube channel, you would see me exclaim that since Malaysia has no rigid plate standard, the training corpus would be very difficult/expensive to realise. It's easier to service Singapore's design.

If you have a need / paying customer for this, I'll be happy to help since I find it an interesting problem to solve.

**Comment by dongzhi-yang** [comment]
Thanks Kai, sure, will keep in touch
